# Feature Engineering

## Objective

This notebook prepares the cleaned student mental health dataset for machine learning.

The preprocessing steps performed include:

- Encoding categorical variables
- Transforming ordinal variables
- Preparing the feature matrix and target variable
- Splitting the dataset into training and testing sets

The processed datasets generated in this notebook will be used for model training.

In [53]:
# ==============================
# Import Required Libraries
# ==============================

import pandas as pd
import numpy as np

# Data Visualization (optional for validation)
import matplotlib.pyplot as plt
import seaborn as sns

# Scikit-learn
from sklearn.model_selection import train_test_split

# Ignore warnings
import warnings
warnings.filterwarnings("ignore")

# Display Settings
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)

# For saving files
import os

In [54]:
clean_df = pd.read_csv(r"D:\Project\Mental-Health-Analyzer-New\ml\data\processed\cleaned_kaggle.csv")

In [55]:
clean_df.head()

clean_df.info()

clean_df.describe()

<class 'pandas.DataFrame'>
RangeIndex: 27812 entries, 0 to 27811
Data columns (total 13 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   Gender                                 27812 non-null  str
 1   Age                                    27812 non-null  int64
 2   Academic Pressure                      27812 non-null  int64
 3   CGPA                                   27812 non-null  float64
 4   Study Satisfaction                     27812 non-null  int64
 5   Sleep Duration                         27812 non-null  str
 6   Dietary Habits                         27812 non-null  str
 7   Degree                                 27812 non-null  str
 8   Have you ever had suicidal thoughts ?  27812 non-null  str
 9   Work/Study Hours                       27812 non-null  int64
 10  Financial Stress                       27812 non-null  int64
 11  Family History of Mental Illness       27812 non-null  str
 12  Depression                             27812 non-null  int64
dtypes: float64(1), int64(6), str(6)
memory usage: 2.8 MB

,Age,Academic Pressure,CGPA,Study Satisfaction,Work/Study Hours,Financial Stress,Depression
count,27812.000000,27812.000000,27812.000000,27812.000000,27812.000000,27812.000000,27812.000000
mean,25.795628,3.142456,7.658569,2.944341,7.160255,3.139508,0.586150
std,4.861796,1.380291,1.466187,1.360272,3.706283,1.437424,0.492531
min,18.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000
25%,21.000000,2.000000,6.290000,2.000000,4.000000,2.000000,0.000000
50%,25.000000,3.000000,7.770000,3.000000,8.000000,3.000000,1.000000
75%,30.000000,4.000000,8.920000,4.000000,10.000000,4.000000,1.000000
max,34.000000,5.000000,10.000000,5.000000,12.000000,5.000000,1.000000

In [56]:
print(f"Dataset Shape : {clean_df.shape}")

clean_df.info()

Dataset Shape : (27812, 13)
<class 'pandas.DataFrame'>
RangeIndex: 27812 entries, 0 to 27811
Data columns (total 13 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   Gender                                 27812 non-null  str
 1   Age                                    27812 non-null  int64
 2   Academic Pressure                      27812 non-null  int64
 3   CGPA                                   27812 non-null  float64
 4   Study Satisfaction                     27812 non-null  int64
 5   Sleep Duration                         27812 non-null  str
 6   Dietary Habits                         27812 non-null  str
 7   Degree                                 27812 non-null  str
 8   Have you ever had suicidal thoughts ?  27812 non-null  str
 9   Work/Study Hours                       27812 non-null  int64
 10  Financial Stress                       27812 non-null  int64
 11  Family History of Mental Illness       27812 non-null  str
 12  Depression                             27812 non-null  int64
dtypes: float64(1), int64(6), str(6)
memory usage: 2.8 MB

## Dataset Overview

The cleaned dataset is now loaded successfully.

Before preparing the dataset for machine learning, each feature is categorized according to its data type.

This helps determine the most appropriate preprocessing technique for every variable.

In [57]:
feature_info = pd.DataFrame({

    "Feature":[

        "Gender",

        "Age",

        "Academic Pressure",

        "CGPA",

        "Study Satisfaction",

        "Sleep Duration",

        "Dietary Habits",

        "Degree",

        "Have you ever had suicidal thoughts ?",

        "Work/Study Hours",

        "Financial Stress",

        "Family History of Mental Illness",

        "Depression"

    ],

    "Type":[

        "Binary",

        "Numerical",

        "Ordinal",

        "Numerical",

        "Ordinal",

        "Ordinal",

        "Ordinal",

        "Nominal",

        "Binary",

        "Numerical",

        "Ordinal",

        "Binary",

        "Target"

    ]

})

feature_info

                                  Feature       Type
0                                  Gender     Binary
1                                     Age  Numerical
2                       Academic Pressure    Ordinal
3                                    CGPA  Numerical
4                      Study Satisfaction    Ordinal
5                          Sleep Duration    Ordinal
6                          Dietary Habits    Ordinal
7                                  Degree    Nominal
8   Have you ever had suicidal thoughts ?     Binary
9                        Work/Study Hours  Numerical
10                       Financial Stress    Ordinal
11       Family History of Mental Illness     Binary
12                             Depression     Target

## Feature Engineering Strategy

Different preprocessing techniques are required for different feature types.

| Feature Type | Technique |
|--------------|-----------|
| Numerical | Keep As It Is |
| Binary | Binary Encoding |
| Ordinal | Ordinal Encoding |
| Nominal | One-Hot Encoding |

## Ordinal Encoding

Some categorical variables possess an inherent ordering.

Examples include:

Sleep Duration

Less than 5 hours

↓

5-6 hours

↓

7-8 hours

↓

More than 8 hours

Encoding these variables preserves the ordinal relationship while making them suitable for machine learning algorithms.

In [58]:
clean_df["Sleep Duration"].unique()

<StringArray>
[''5-6 hours'', ''Less than 5 hours'', ''7-8 hours'', ''More than 8 hours'']
Length: 4, dtype: str

In [59]:
clean_df["Sleep Duration"] = (
    clean_df["Sleep Duration"]
    .str.replace("'", "", regex=False)
    .str.strip()
)

In [60]:
sleep_mapping = {

    "Less than 5 hours":0,

    "5-6 hours":1,

    "7-8 hours":2,

    "More than 8 hours":3

}

clean_df["Sleep Duration"] = clean_df["Sleep Duration"].map(sleep_mapping)

In [61]:
diet_mapping = {

    "Unhealthy":0,

    "Moderate":1,

    "Healthy":2

}

clean_df["Dietary Habits"] = clean_df["Dietary Habits"].map(diet_mapping)

In [62]:
binary_mapping = {

    "Yes":1,

    "No":0

}

clean_df["Have you ever had suicidal thoughts ?"] = clean_df["Have you ever had suicidal thoughts ?"].map(binary_mapping)

clean_df["Family History of Mental Illness"] = clean_df["Family History of Mental Illness"].map(binary_mapping)

In [63]:
gender_mapping = {

    "Male":1,

    "Female":0

}

clean_df["Gender"] = clean_df["Gender"].map(gender_mapping)

## One-Hot Encoding

Unlike ordinal variables, academic degrees have no natural ordering.

Assigning numerical values such as

B.Tech = 1

MBA = 2

MBBS = 3

would incorrectly imply a ranking.

Therefore, One-Hot Encoding is used.

In [64]:
clean_df = pd.get_dummies(

    clean_df,

    columns=["Degree"],

    drop_first=True,

    dtype=int

)

In [65]:
clean_df.head()

,Gender,Age,Academic Pressure,CGPA,Study Satisfaction,Sleep Duration,Dietary Habits,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression,Degree_B.Arch,Degree_B.Com,Degree_B.Ed,Degree_B.Pharm,Degree_B.Tech,Degree_BA,Degree_BBA,Degree_BCA,Degree_BE,Degree_BHM,Degree_BSc,Degree_LLB,Degree_LLM,Degree_M.Com,Degree_M.Ed,Degree_M.Pharm,Degree_M.Tech,Degree_MA,Degree_MBA,Degree_MBBS,Degree_MCA,Degree_MD,Degree_ME,Degree_MHM,Degree_MSc,Degree_Others,Degree_PhD
0,1,33,5,8.97,2,1,2,1,3,1,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,0,24,2,5.90,5,1,1,0,3,2,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,1,31,3,7.03,5,0,2,0,9,1,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,0,28,3,5.59,2,2,1,1,4,5,1,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,0,25,4,8.13,3,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0

In [66]:
X = clean_df.drop(columns=["Depression"])

y = clean_df["Depression"]

print("Feature Matrix :",X.shape)

print("Target :",y.shape)

Feature Matrix : (27812, 38)
Target : (27812,)

## Train-Test Split

The dataset is divided into training and testing subsets.

- Training Set : 80%
- Testing Set : 20%

Stratified sampling is employed to preserve the class distribution of the target variable in both subsets.

In [67]:
X_train,X_test,y_train,y_test = train_test_split(

    X,

    y,

    test_size=0.2,

    random_state=42,

    stratify=y

)

In [68]:
print("Training Features :",X_train.shape)

print("Testing Features :",X_test.shape)

print("Training Labels :",y_train.shape)

print("Testing Labels :",y_test.shape)

Training Features : (22249, 38)
Testing Features : (5563, 38)
Training Labels : (22249,)
Testing Labels : (5563,)

In [69]:
import os

os.makedirs(r"D:\Project\Mental-Health-Analyzer-New\ml\data\final",exist_ok=True)

X_train.to_csv(r"D:\Project\Mental-Health-Analyzer-New\ml\data\final\X_train.csv",index=False)

X_test.to_csv(r"D:\Project\Mental-Health-Analyzer-New\ml\data\final\X_test.csv",index=False)

y_train.to_csv(r"D:\Project\Mental-Health-Analyzer-New\ml\data\final\y_train.csv",index=False)

y_test.to_csv(r"D:\Project\Mental-Health-Analyzer-New\ml\data\final\y_test.csv",index=False)

print("Processed datasets saved successfully.")

Processed datasets saved successfully.

# Summary

The cleaned student mental health dataset has been successfully transformed into a machine learning ready format.

The following preprocessing steps were performed:

- Removed non-essential features
- Applied ordinal encoding
- Applied binary encoding
- Performed One-Hot Encoding
- Created the feature matrix and target variable
- Split the dataset into training and testing subsets
- Saved processed datasets for model development

The processed data generated in this notebook will serve as the foundation for model training in the next stage of the project.